server:
  port: 8080
  servlet:
    context-path: /ssm
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false
